config/routes.rb
Rails.application.routes.draw do
  resources :kit_instances, only: [ :create, :update, :destroy ]
  resources :materials
  resources :kits
  resources :source_materials
  resources :kit_scales
  resources :kit_lines
  resources :producers
  resources :designers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/kit.rb
class Kit < ApplicationRecord
  has_and_belongs_to_many :designers
  has_and_belongs_to_many :kit_lines
  has_and_belongs_to_many :materials
  has_and_belongs_to_many :producers
  has_and_belongs_to_many :source_materials
  has_and_belongs_to_many :kit_links,
    class_name: "Kit",
    join_table: "kit_links",
    foreign_key: "kit_linked_from_id",
    association_foreign_key: "kit_linked_to_id"
  has_and_belongs_to_many :kit_back_links,
    class_name: "Kit",
    join_table: "kit_links",
    foreign_key: "kit_linked_to_id",
    association_foreign_key: "kit_linked_from_id"

  belongs_to :kit_scale

  has_many :kit_instances, dependent: :destroy
  accepts_nested_attributes_for :kit_instances

  STATUSES = KitInstance::STATUSES

  # Virtual attr to simplify logic of creating or not creating instances in creation form
  attr_accessor :persist_box

  before_validation :set_guid, unless: :persisted?

  validates :name, presence: true

  delegate :name, to: :kit_scale, prefix: true
  alias_method :scale_name, :kit_scale_name

  def material_names
    materials.pluck(:name)
  end

  def producer_names
    producers.pluck(:name)
  end

  def kit_line_names
    kit_lines.pluck(:name)
  end

  def quantity
    kit_instances.count
  end

  def handle
    elements = [
      name,
      kit_scale_name,
      kit_lines.map(&:nickname).then {|arr| arr.empty? ? nil : "[#{arr.join(', ')}]"},
      producers.pluck(:name).then {|arr| arr.empty? ? nil : "[#{arr.join(', ')}]"},
    ]
      .reject(&:blank?)

    elements.join(' ')
  end

  private

  def set_guid
    return if persisted? || self.guid.present?

    self.guid = "#{name.parameterize}__#{SecureRandom.uuid}"
  end
end

app/controllers/kits_controller.rb
class KitsController < ApplicationController
  before_action :set_kit, only: %i[ show edit update destroy ]

  # GET /kits or /kits.json
  def index
    statuses = KitInstance::Status.normalize(params.fetch(:status, ''))

    @kit_instances = KitInstance.by_status(statuses)
    @kits = Kit.where(kit_instances: @kit_instances)
  end

  # GET /kits/1 or /kits/1.json
  def show
    @kit_instance = @kit.kit_instances.build(kit: @kit)
  end

  # GET /kits/new
  def new
    @create_boxes = true
    @kit = Kit.new(materials: [Material.find_by(name: 'Plastic')]).tap {|kit| kit.kit_instances.build }
  end

  # GET /kits/1/edit
  def edit
    @create_boxes = false
  end

  # POST /kits or /kits.json
  def create
    @kit = Kit.new(kit_params)

    respond_to do |format|
      if @kit.save
        format.html { redirect_to kits_url, notice: "Kit was successfully created." }
        format.json { render :show, status: :created, location: @kit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kits/1 or /kits/1.json
  def update
    respond_to do |format|
      if @kit.update(kit_params)
        format.html { redirect_to kit_url(@kit), notice: "Kit was successfully updated." }
        format.json { render :show, status: :ok, location: @kit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kits/1 or /kits/1.json
  def destroy
    @kit.destroy

    respond_to do |format|
      format.html { redirect_to kits_url, notice: "Kit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_kit
    @kit = Kit.find(params[:id])
  end

  def kit_params
    submitted = params.require(:kit)
      .permit(
        :name,
        :status,
        :notes,
        :quantity,
        :kit_scale_id,
        :persist_box,
        material_ids: [],
        producer_ids: [],
        kit_line_ids: [],
        designer_ids: [],
        source_material_ids: [],
        kit_link_ids: [],
        kit_instances_attributes: [
          :status,
          :notes,
          :location_id,
        ],
      )

    # Supported by Kit#persist_box virtual attr
    persist_box = ActiveModel::Type::Boolean.new.cast(submitted.delete(:persist_box))

    return submitted if persist_box

    submitted.reject {|key, value| key == "kit_instances_attributes"}
  end
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/views/kits/_form.html.haml
.row
  .col
    = bootstrap_form_for(@kit) do |f|
      - if @kit.errors.any?
        #error_explanation
          %h2= "#{pluralize(@kit.errors.count, "error")} prohibited this kit from being saved:"
          %ul
            - @kit.errors.full_messages.each do |message|
              %li= message
      .row
        .col
          = f.text_field :name
        .col
          - kit_scale_options = KitScale.increasing.pluck(:id, :name).map {|id, name| { value: id, label: name }}
          = f.label :kit_scale
          = render('multi_select', name: "kit[kit_scale_id]", current_value: @kit.kit_scale_id, collection: kit_scale_options)
      .row
        .col
          - related_kit_options = Kit.all.map {|k| { value: k.id, label: k.handle }}
          = f.label :related_kits
          = render('multi_select', name: "kit[kit_link_ids][]", current_value: @kit.kit_link_ids, collection: related_kit_options)
        .col
          = f.label :materials
          - material_options = Material.all.pluck(:id, :name).map {|id, name| { value: id, label: name }}
          = render('multi_select', name: "kit[material_ids][]", collection: material_options, current_value: @kit.material_ids)

      .row
        .col
          - producer_options = Producer.all.pluck(:id, :name).map {|id, name| { value: id, label: name }}
          = f.label :producers
          = render('multi_select', name: "kit[producer_ids][]", collection: producer_options, current_value: @kit.producer_ids)

        .col
          - kit_line_options = KitLine.all.pluck(:id, :name).map {|id, name| { value: id, label: name }}
          = f.label :kit_lines
          = render('multi_select', name: "kit[kit_line_ids][]", collection: kit_line_options, current_value: @kit.kit_line_ids)

        .col
          - designer_options = Designer.all.pluck(:id, :name).map {|id, name| { value: id, label: name }}
          = f.label :designers
          = render('multi_select', name: "kit[designer_ids][]", collection: designer_options, current_value: @kit.designer_ids)

      .row
        .col
          = f.label :source_materials
          = render 'multi_select', name: "kit[source_material_ids][]", current_value: @kit.source_material_ids, collection: SourceMaterial.all.pluck(:id, :name, :slug).map {|id, name, slug| { value: id, label: "#{name} (#{slug})" }}

      .row
        .col
          = f.text_area :notes

      - if @create_boxes
        .row.mt-2
          .col
            %h3 Boxes of this kit
            = f.check_box :persist_box, switch: true, label: 'Create a copy of this kit your backlog?', checked: true
            .border.rounded.p-2
              = f.fields_for :kit_instances do |ki_f|
                = ki_f.select :status, KitInstance::STATUSES.keys, selected: "OWNED"
                = ki_f.label :location
                - location_options = Location.pluck(:id, :name).map {|id, name| { value: id, label: name }}
                = render('multi_select', name: 'kit_instance[location_id]', current_value: nil, collection: location_options)
                = ki_f.text_area :notes

      .row.mt-2
        .col
          .actions
            = f.submit 'Save', render_as_button: true

app/views/kits/edit.html.haml
%h1 Editing kit

= render 'form'

= link_to 'Show', @kit
\|
= link_to 'Back', kits_path

app/views/kits/index.html.haml
.row
  .col
    %h1 Kits
.row
  .col
    %table.table.table-sm
      %thead
        %tr
          %th INCOMING
          %th UNBUILT
          %th FINISHED
          %th Total
      %tbody
        %tr
          %td
            - pending = KitInstance::Status::PENDING_DELIVERY
            = link_to KitInstance.where(status: pending).count, kits_path(status: pending)
          %td
            - owned = KitInstance::Status::OWNED
            = link_to KitInstance.where(status: owned).count, kits_path(status: owned)
          %td
            - built = KitInstance::Status::BUILT
            = link_to KitInstance.where(status: built).count, kits_path(status: built)
          %td= link_to KitInstance.count, kits_path
.row
  .col
    = link_to 'Create a new kit', new_kit_path
.row
  .col
    %table.table.table-striped.table-sm
      %thead
        %tr
          %th Name
          %th Quantity
          %th Scale
          %th Materials
          %th Producers
          %th Kit lines
          %th
          %th

      %tbody
        - @kits.each do |kit|
          %tr
            %td
              = link_to kit.name, kit_path(kit)
            %td= kit.quantity
            %td= kit.scale_name
            %td
              - kit.materials.each do |material|
                = link_to material.name, material_path(material)
            %td
              - kit.producers.each do |producer|
                = link_to producer.name, producer_path(producer)
            %td
              - kit.kit_lines.each do |kit_line|
                = link_to kit_line.name, kit_line_path(kit_line)
            %td= link_to 'Edit', edit_kit_path(kit), class: 'btn btn-sm btn-outline-primary'
            %td= button_to 'Destroy', kit, class: 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' }

app/views/kits/new.html.haml
%h1 New kit

= render 'form'

= link_to 'Back', kits_path

app/views/kits/show.html.haml
.row.mt-2
  .col.col-md-10
    %h1= @kit.name
  .col
    = link_to 'Edit', edit_kit_path(@kit), class: 'btn btn-sm btn-outline-primary mb-1 float-start'
    = button_to 'Destroy', @kit, class: 'btn btn-sm btn-outline-danger float-end', method: :delete, data: { confirm: 'Are you sure?' }

.row.mt-4
  .col
    %h3 Producers
    %ul
      - @kit.producers.each do |producer|
        %li= link_to producer.name, producer_path(producer)
  .col
    %h3 Kit lines
    %ul
      - @kit.kit_lines.each do |kit_line|
        %li= link_to kit_line.name, kit_line_path(kit_line)
  .col
    %h3 Designers
    %ul
      - @kit.designers.each do |designer|
        %li= link_to designer.name, designer_path(designer)
  .col
    %h3 Source materials
    %ul
      - @kit.source_materials.each do |source_material|
        %li
          %a{href: source_material_path(source_material)}
            = source_material.name
            %code= source_material.slug

.row.mt-4
  .col
    %h3 Quantity
    %p= @kit.quantity
  .col
    %h3 Materials
    %ul
      - @kit.materials.each do |material|
        %li= link_to material.name, material_path(material)
  .col
    %h3 Linked kits
    %ul
      - @kit.kit_links.each do |rk|
        %li= link_to rk.name, kit_path(rk)
  .col
    %h3 Kit backlinks
    %ul
      - @kit.kit_back_links.each do |bk|
        %li= link_to bk.name, kit_path(bk)

.row
  .col
    %h3 Notes
    - if @kit.notes.blank?
      %em none
    - else
      %p= @kit.notes

.row.mt-2
  .col
    %h3 Copies of this kit
    .row
      - @kit.kit_instances.persisted.each do |ki|
        .col.col-md-4.mt-1
          .border.border-2.rounded.mx-1.p-2
            = bootstrap_form_for(ki) do |f|
              = f.select :status, KitInstance::STATUSES.keys
              = f.label :location
              - location_options = Location.pluck(:id, :name).map {|id, name| { value: id, label: name }}
              = render('multi_select', name: 'kit_instance[location_id]', current_value: ki.location_id, collection: location_options)
              = f.text_area :notes
              = f.submit 'Update', class: 'btn btn-outline-primary btn-sm float-start'
            = button_to 'Destroy', ki, class: 'btn btn-sm btn-outline-danger float-end', method: :delete, data: { confirm: 'Are you sure?' }
            .clearfix

.row.mt-4
  .col
    %h3 Add another copy of this kit
    = bootstrap_form_for(@kit_instance) do |f|
      - if @kit_instance.errors.any?
        #error_explanation
          %h2= "#{pluralize(@kit_instance.errors.count, "error")} prohibited this kit_instance from being saved:"
          %ul
            - @kit_instance.errors.full_messages.each do |message|
              %li= message
      = f.hidden_field :kit_id
      = f.select :status, KitInstance::STATUSES.keys
      = f.text_area :notes
      = f.submit 'Save copy', class: 'btn btn-outline-primary'