config/routes.rb
Rails.application.routes.draw do
  resources :kit_instances, only: [ :create, :update, :destroy ]
  resources :materials
  resources :kits
  resources :source_materials
  resources :kit_scales
  resources :kit_lines
  resources :producers
  resources :designers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/designer.rb
class Designer < ApplicationRecord
  has_and_belongs_to_many :kits

  validates :name, presence: true, uniqueness: true
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :set_designer, only: %i[ show edit update destroy ]

  # GET /designers or /designers.json
  def index
    @designers = Designer.all
  end

  # GET /designers/1 or /designers/1.json
  def show
  end

  # GET /designers/new
  def new
    @designer = Designer.new
  end

  # GET /designers/1/edit
  def edit
  end

  # POST /designers or /designers.json
  def create
    @designer = Designer.new(designer_params)

    respond_to do |format|
      if @designer.save
        format.html { redirect_to designer_url(@designer), notice: "Designer was successfully created." }
        format.json { render :show, status: :created, location: @designer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designers/1 or /designers/1.json
  def update
    respond_to do |format|
      if @designer.update(designer_params)
        format.html { redirect_to designer_url(@designer), notice: "Designer was successfully updated." }
        format.json { render :show, status: :ok, location: @designer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designers/1 or /designers/1.json
  def destroy
    @designer.destroy

    respond_to do |format|
      format.html { redirect_to designers_url, notice: "Designer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_designer
    @designer = Designer.find(params[:id])
  end

  def designer_params
    params.require(:designer).permit(:name)
  end
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/views/designers/_form.html.haml
.row
  .col
    = bootstrap_form_for(@designer) do |f|
      - if @designer.errors.any?
        #error_explanation
          %h2= "#{pluralize(@designer.errors.count, "error")} prohibited this designer from being saved:"
          %ul
            - @designer.errors.full_messages.each do |message|
              %li= message

      .row
        .col
          = f.text_field :name
          = f.submit 'Save'

app/views/designers/edit.html.haml
%h1 Editing designer

= render 'form'

= link_to 'Show', @designer
\|
= link_to 'Back', designers_path

app/views/designers/index.html.haml
.row
  .col
    %h1 Designers
.row
  .col
    = link_to 'Create a new designer', new_designer_path
.row
  .col
    %table.table.table-striped.table-sm
      %thead
        %tr
          %th Name
          %th

      %tbody
        - @designers.each do |designer|
          %tr
            %td= designer.name
            %td= link_to 'Show', designer, class: 'btn btn-sm btn-outline-primary'
            %td= link_to 'Edit', edit_designer_path(designer), class: 'btn btn-sm btn-outline-primary'
            %td= button_to 'Destroy', designer, class: 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' }

app/views/designers/new.html.haml
%h1 New designer

= render 'form'

= link_to 'Back', designers_path

app/views/designers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_designer_path(@designer)
\|
= link_to 'Back', designers_path