config/routes.rb
Rails.application.routes.draw do
  resources :kit_instances, only: [ :create, :update, :destroy ]
  resources :materials
  resources :kits
  resources :source_materials
  resources :kit_scales
  resources :kit_lines
  resources :producers
  resources :designers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/kit_line.rb
class KitLine < ApplicationRecord
  belongs_to :producer

  validates :name, presence: true, uniqueness: true
  validates :nickname, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true

  before_validation :set_name_as_nickname_if_blank

  def nickname
    super || name
  end

  private

  def set_name_as_nickname_if_blank
    return if nickname.present?

    self.nickname = name
  end
end

app/controllers/kit_lines_controller.rb
class KitLinesController < ApplicationController
  before_action :set_kit_line, only: %i[ show edit update destroy ]

  # GET /kit_lines or /kit_lines.json
  def index
    @kit_lines = KitLine.all
  end

  # GET /kit_lines/1 or /kit_lines/1.json
  def show
  end

  # GET /kit_lines/new
  def new
    @kit_line = KitLine.new
  end

  # GET /kit_lines/1/edit
  def edit
  end

  # POST /kit_lines or /kit_lines.json
  def create
    @kit_line = KitLine.new(kit_line_params)

    respond_to do |format|
      if @kit_line.save
        format.html { redirect_to kit_line_url(@kit_line), notice: "Kit line was successfully created." }
        format.json { render :show, status: :created, location: @kit_line }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kit_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kit_lines/1 or /kit_lines/1.json
  def update
    respond_to do |format|
      if @kit_line.update(kit_line_params)
        format.html { redirect_to kit_line_url(@kit_line), notice: "Kit line was successfully updated." }
        format.json { render :show, status: :ok, location: @kit_line }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kit_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kit_lines/1 or /kit_lines/1.json
  def destroy
    @kit_line.destroy

    respond_to do |format|
      format.html { redirect_to kit_lines_url, notice: "Kit line was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kit_line
      @kit_line = KitLine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kit_line_params
      params.fetch(:kit_line, {})
    end
end

app/helpers/kit_lines_helper.rb
module KitLinesHelper
end

app/views/kit_lines/_form.html.haml
= form_for @kit_line do |f|
  - if @kit_line.errors.any?
    #error_explanation
      %h2= "#{pluralize(@kit_line.errors.count, "error")} prohibited this kit_line from being saved:"
      %ul
        - @kit_line.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/kit_lines/edit.html.haml
%h1 Editing kit_line

= render 'form'

= link_to 'Show', @kit_line
\|
= link_to 'Back', kit_lines_path

app/views/kit_lines/index.html.haml
%h1 Listing kit_lines

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @kit_lines.each do |kit_line|
      %tr
        %td= link_to 'Show', kit_line
        %td= link_to 'Edit', edit_kit_line_path(kit_line)
        %td= link_to 'Destroy', kit_line, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Kit line', new_kit_line_path

app/views/kit_lines/new.html.haml
%h1 New kit_line

= render 'form'

= link_to 'Back', kit_lines_path

app/views/kit_lines/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_kit_line_path(@kit_line)
\|
= link_to 'Back', kit_lines_path