config/routes.rb
Rails.application.routes.draw do
  resources :kit_instances, only: [ :create, :update, :destroy ]
  resources :materials
  resources :kits
  resources :source_materials
  resources :kit_scales
  resources :kit_lines
  resources :producers
  resources :designers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/producer.rb
class Producer < ApplicationRecord
  has_and_belongs_to_many :kits

  validates :name, presence: true, uniqueness: true
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :set_producer, only: %i[ show edit update destroy ]

  # GET /producers or /producers.json
  def index
    @producers = Producer.all
  end

  # GET /producers/1 or /producers/1.json
  def show
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit
  end

  # POST /producers or /producers.json
  def create
    @producer = Producer.new(producer_params)

    respond_to do |format|
      if @producer.save
        format.html { redirect_to producer_url(@producer), notice: "Producer was successfully created." }
        format.json { render :show, status: :created, location: @producer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producers/1 or /producers/1.json
  def update
    respond_to do |format|
      if @producer.update(producer_params)
        format.html { redirect_to producer_url(@producer), notice: "Producer was successfully updated." }
        format.json { render :show, status: :ok, location: @producer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1 or /producers/1.json
  def destroy
    @producer.destroy

    respond_to do |format|
      format.html { redirect_to producers_url, notice: "Producer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producer
      @producer = Producer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producer_params
      params.fetch(:producer, {})
    end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.haml
= form_for @producer do |f|
  - if @producer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@producer.errors.count, "error")} prohibited this producer from being saved:"
      %ul
        - @producer.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/producers/edit.html.haml
%h1 Editing producer

= render 'form'

= link_to 'Show', @producer
\|
= link_to 'Back', producers_path

app/views/producers/index.html.haml
%h1 Listing producers

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @producers.each do |producer|
      %tr
        %td= link_to 'Show', producer
        %td= link_to 'Edit', edit_producer_path(producer)
        %td= link_to 'Destroy', producer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Producer', new_producer_path

app/views/producers/new.html.haml
%h1 New producer

= render 'form'

= link_to 'Back', producers_path

app/views/producers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_producer_path(@producer)
\|
= link_to 'Back', producers_path